### ISSUE TITLE
[BUG] Spectator without grim access seeing a demon "Dead" reminder appear when night death is revealed

### ISSUE THREAD

**Issue by Dazli** [ThePandemoniumInstitute/botc-release#255] opened 2024-10-20 20:55 UTC
### Description

As a spectator without grim access I suddenly saw an Imp "Dead" reminder token appear when a night death was revealed in the morning. I'm using Chrome on Win11. The script was Trouble Brewing, 12 players, solo ST. The player whom the reminder appeared on was the Undertaker. Refreshing did not remove the reminder. The console log only contains Unknown VE context: -errors containing background-position, transition, and -moz-osx-font-smoothing

![image](https://github.com/user-attachments/assets/ff023748-88d2-4218-b4e0-c15f60aa504c)
![image](https://github.com/user-attachments/assets/11fa23d0-ccf7-4b37-97ba-4b32fc6c38bb)

### Browser

Chrome

### Operating System

Windows

### Date and Time

October 20th 2024, 11:40-11:50pm UTC+3

### Game Session

fc_botc

**Comment by bra1n** [comment] 2024-10-21 09:56
Hey there, I looked into the logs and I can see when your ST added the shroud at the beginning of the next day, however this actually _removed_ the "Dead" reminder token they had previously placed there due to the Imp's ability. It should not have triggered a new "Dead" reminder token for anyone in the game. I was unfortunately also unable to reproduce this issue - I tried switching from Night to Day and then adding a shroud just like in your situation, but for the spectators there weren't any new reminders showing up.
If it happens again, it would be great if you could figure out what exactly might be causing it. As for now, it seems like it was a weird one-time glitch, so I'll close this issue until we have new information.

**Closed by bra1n** 2024-10-21 09:56 UTC
Labels: bug, triage

**Comment by Dazli** [comment] 2024-10-21 12:46
the reminder may have been present already during the night, that's something I can't 100% confirm whether it happened in the night time or during the actual morning reveal - I only suddenly realized it during the morning discussion before people started heading off for daytime chats

**Comment by bra1n** [comment] 2024-10-21 13:44
If it's the only Storyteller aspect you saw as a spectator, then it's unlikely that it was actual storyteller action leaking to your app. What seems more likely is that you somehow got an extra "Dead" reminder token show up, but I'm not sure how that would have happened - and I was also unable to reproduce it when I tried it. :-/
