### ISSUE TITLE
[FEATURE] Setting to disable touch screen hand raising/lowering?

### ISSUE THREAD

**Issue by Ash-42** [ThePandemoniumInstitute/botc-release#267] opened 2024-11-04 04:23 UTC
### What problem are you trying to solve?

I keep accidentally raising my hand when trying to use the touch screen on my laptop, presumably because of the new swiping feature for mobile. This is triggered by just tapping as well as actually swiping. This is only mildly annoying most of the day, but it has led to accidental voting because I forgot I couldn't use the touch screen to check messages/the script during nominations anymore.

### Describe the solution you'd like

A setting to disable hand raising and lowering by swiping (and/or other modification of the new feature) so people can use touch screens without raising their hands

### Alternatives you have considered

Adjustment so that tapping the screen won't register as swiping; having touching specifically the side tabs (and pop-out boxes) not affect hands

**Comment by bra1n** [comment] 2024-11-04 14:40
Hey there, this seems to be a duplicate of #264, so I'll close this ticket. I also plan to decrease the sensitivity for swipe detection with the next update, so that it will be much better usable on touch devices again. :slightly_smiling_face:

**Closed by bra1n** 2024-11-04 14:40 UTC
Labels: feature, triage
