### ISSUE TITLE
[BUG] Off center text when changing screens

### ISSUE THREAD

**Issue by hwarden162** [ThePandemoniumInstitute/botc-release#250] opened 2024-10-07 20:19 UTC
### Description

I had my laptop connected to a monitor, I then disconnected the laptop from the monitor moving the broswer window to the laptop screen. This then off centers the text on the reminder tokens and the gong.

![image](https://github.com/user-attachments/assets/b948a7ea-1aa9-448e-9c10-b37dc19ac50b)

![image](https://github.com/user-attachments/assets/61ca923b-9c11-44e1-8cf5-4115f2341d67)

### Steps to reproduce

Connect laptop to external monitor with different screen size/resolution

Open Join official app on larger screen/resolution.

Disconnect and open on smaller resolution.

### Browser

Firefox

### Operating System

Mac

### Date and Time

Mon 7th Oct; 21:00 BST

### Game Session

paradox

**Comment by bra1n** [comment] 2024-10-08 08:16
Hey there, this is a duplicate of #245, which will be fixed with the upcoming update.

**Closed by bra1n** 2024-10-08 08:16 UTC
Labels: bug, triage
