### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by howlieT** [ThePandemoniumInstitute/botc-release#176] opened 2024-04-30 20:32 UTC
### Description

When playing a session as the banshee, I was killed by a harpy rather than by a demon, the app still offered me a double hands up option. 

This also allows the town to fully confirm that the banshee is who they say they are, if for example they die on a night alongside another death, rather than allowing them to hide
![Screenshot 2024-04-30 at 21 27 45](https://github.com/ThePandemoniumInstitute/botc-release/assets/96737330/d34e6b73-f70f-4ad3-8b63-c3d3b1ab8c0a)
![Screenshot 2024-04-30 at 21 27 57](https://github.com/ThePandemoniumInstitute/botc-release/assets/96737330/4eb42c81-af35-4616-aafd-996fbdca6a67)

### Steps to reproduce

Running the game, have the banshee player die by any means

### Browser

Chrome

### Operating System

Mac

### Date and Time

April 30th 21:32 GMT

### Game Session

voles

### Relevant console log output

```shell
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
chat-eu3.botc.app:3016/health:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
contentScript.js:1 P Received SHOW_SIDEBAR_APP action in content script
app.28c7d405.js:1 
 GET https://chat-eu3.botc.app:3016/health net::ERR_CONNECTION_REFUSED
﻿
```

**Comment by bra1n** [comment] 2024-05-02 10:03
Hi Misha, thank you for the bug report! However, this is not a bug.
Just like in real life, anybody can put up both their hands and claim they are the Banshee. If it only allowed the *real* Banshee to do that, it would hard confirm who is or is not the Banshee and whether they are poisoned or not. Basically, any player that is dead and has the Banshee assigned to their own token on their player Grimoire has the ability to raise both hands during a vote. However, only the *real* Banshee will get both hands counted by the Storyteller in the app, and anybody else having both hands up while not being the real Banshee will spend their ghost vote token and still only cast a single vote during that nomination.
I hope that clears it up. :-)

**Closed by bra1n** 2024-05-02 10:03 UTC
Labels: bug, triage

**Comment by howlieT** [comment] 2024-05-02 22:46
Just to clarify, does this mean anyone wishing to bluff as banshee would need to set themselves as that token on the grimoire and then would see the option to raise two hands?

**Comment by bra1n** [comment] 2024-05-03 07:03
Yes, that is correct, as long as they are dead. If they do raise both hands while being some other character than the Banshee on the Storyteller Grimoire, they will spend their ghost vote token and still only cast one vote, though.
