### ISSUE TITLE
[BUG] Vote display does not take into account votes that happened when majority was higher

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#238] opened 2024-09-22 21:54 UTC
### Description

There are 9 players alive. A vote occurs displaying "The majority is 5 votes" in which a player got 4 votes. 
A player then nominates and dies due to the Witch. There are 8 players alive. The pop-up displays "The majority is 4 votes" and the vote gets 3 votes. Another vote occurs and the pop-up still displays "The majority is 4 votes". While technically correct, this is unhelpful because 5 votes are actually required to execute anyone. An execution requires the uniquely highest number of votes AND be a majority of town. In this case 4 votes would be a tie with the player who received 4 votes prior to the alive player count decreasing.

Here's a clip of the bug in action
https://www.twitch.tv/impinthenorth/clip/SuccessfulFuriousClipsmomChefFrank-NLTKqfs1r9W6Kh67

### Steps to reproduce

Make a nomination with an odd number of players (for convenience so only 1 death is required to change majority)
That vote gets 1 less than the majority required.
Kill a player during the day
Run another vote. The majority indicated will result in a tie. This should say "5 votes are required" similar to when someone is on the block

### Browser

Chrome

### Operating System

Windows

### Date and Time

22nd September 2024, ~22:40 BST

**Comment by bra1n** [comment] 2024-09-23 07:27
Hey Geoff, while you're correct that the vote in the above situation would not cause the second player to be marked for execution, I feel like this is something that is mostly on the Storyteller to announce, rather than the app. And as you pointed out, the app doesn't show "X votes to execute", but rather "majority is X"  in this case. So this is definitely not a bug, and as a feature request it would probably be "consider edge cases for vote count rules", which would never be a perfect system, given the complex rules of the game.
I'll close this ticket for now, as it's not a bug and because I feel like the above situation is something that should be handled by the Storyteller themselves, first and foremost.

**Closed by bra1n** 2024-09-23 07:27 UTC
Labels: bug, triage
