### ISSUE TITLE
Can't enter private chats

### ISSUE THREAD

**Issue by Kayllain** [ThePandemoniumInstitute/botc-release#156] opened 2024-04-18 04:14 UTC
**Describe the bug**
When invited into a private chat, I'm unable to enter the room by clicking the checkmark, or by hitting the associated number with the chat. clicking the number or pushing the button has no result, the only way to get into the room is to open my own chat with the player or have them send the request again.

**To Reproduce**
Reproducing the error should be simple, it happens fairly often when you are invited to chat

**Expected behavior**
I expected to be able to accept the chat and enter the private room either by clicking on the check or hitting the number that matched with the chat request.

**Browser app (please complete the following information):**
Windows 11
Chrome
Version 123.0.6312.123

**Comment by bra1n** [comment] 2024-04-19 09:06
Hey Kallain, thanks for the bug report! Would it be possible for you to record a brief video of the issue? And check for any console log messages? As it is, I'm unable to reproduce this issue - for me, accepting a chat request always works as it should, both with shortcut key and clicking.

**Comment by moutonf** [comment] 2024-04-25 13:46
I can perhaps add some additional insight into this. The UI works very well with a lower player count. When the player count goes above 12, typically at 15 or so, the amount of private chats start overflowing the space for voice chat, and the voice chat ends up going off the top of the screen.

Partially also want to add an issue that was in 3.23.2 is that when the voice chat was over the story teller button, one was unable to click on the tick mark to accept it, as it would try to select the object behind it (story teller). This was actually addressed in 3.24.0 and is no longer an issue.

Feature suggestion on this would be to limit the height of the voice chat box and not allow it to overflow the top of the window (if this is possible).

**Closed** 2024-04-29 12:02 UTC
Labels: bug, question
